[package]
name = "debug-derive"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "2.0.66", features = ["extra-traits"] }
quote = "1.0.36"
proc-macro2 = "1.0.86"

[dev-dependencies]
trybuild = { version = "1.0.49", features = ["diff"] }

[lib]
proc-macro=true